### PR TITLE
Adjust button movement dinamically to panel height changes

### PR DESCRIPTION
**Pull request by Knight81**
This change makes the button move correctly when the panel height is changed in setPanelHeight

### CODE REVIEW

**Comment by taltstidl** [comment]
@Knight81 Thanks for your pull request! Does this solve your issue? 
For your information: I currently don't have access to my development computer I'll merge it later (probably sometime in Oktober, yeah I know, that late).

**Comment by Knight81** [comment]
Yes,i was going to close it but i forgot,going to close it know.
No problem for now i'm working with my fork but would like to use yours when it's merged,by the way,awesome library ^^

**Comment by taltstidl** [comment]
@Knight81 Thank you :smiley:! And thanks for your fix!

**Comment by taltstidl** [comment]
@Knight81 I finally got around to merging this along with updates from the original repo. You'll be able to update to version 3.2.1 soon.

**Pull request merged**
