### PR TITLE
Update from original library

### PR DESCRIPTION
**Pull request by taltstidl**

### CODE REVIEW

**Comment by blurpy** [comment]
Since it's taking time to get this merged into upstream, it would be great if you could merge from upstream. I'd really like to have the scrollable child view support just released in 3.1.

**Comment by taltstidl** [comment]
@blurpy Yep, I totally will merge this new feature. Unfortunately I won't be able to access my development computer for a while, so you'll have to wait until the very beginning of August.

**Comment by blurpy** [comment]
That's OK, thanks!

**Comment by taltstidl** [comment]
@blurpy I merged from upstream today. Please update to version `3.1.2` to get the scrollable view support (this also includes `RecyclerView` unlike the current maven version of the original).

**Comment by blurpy** [comment]
@TR4Android Thanks a lot! Can't wait to test this.

**Comment by blurpy** [comment]
Oh no, I'm still affected by this: https://code.google.com/p/android/issues/detail?id=175140
I can't use this version as it pulls in the non-working version of the support library.

**Comment by taltstidl** [comment]
@blurpy I could theoretically use a out of date support library for this, but then I'd have to do more releases and it'll confuse other users of the library.
You could follow the instructions in my [Readme](https://github.com/TR4Android/AndroidSlidingUpPanel/blob/master/README.md) though. There's an explanation on how you can download the repo and manually include it (Importing the library - Download as zip file). The only change you'd have to make would be in `build.gradle`, reverting to older support library versions.
Otherwise you could just wait for a support library release with the fix.

**Comment by blurpy** [comment]
@TR4Android Thanks, I was already using this repo as a git submodule. Have been using your fork since before you added the repo.

Google can be so slow when it comes to bug fixes, so I don't expect this to be fixed for a while.

I forked your repo and downgraded the support library. Also had to remove support for RecyclerView as it too was causing crashes with the Toolbar. I first tried downgrading it, but then it wouldn't compile.

You can see the changes here: https://github.com/blurpy/AndroidSlidingUpPanel/commit/65f6b9cac9f232f2beeea6880bcf7044b7b38f4c

The scrolling works so much better in my app after this update though, so I'm happy so far.

**Comment by taltstidl** [comment]
@blurpy Yes, Google's update philosophy can be quite annoying at times, especially when important bug fixes don't make it into the next release.
I'll try to keep the version up to date as new versions get released. Let's see when the fix is actually in one.

**Comment by blurpy** [comment]
@TR4Android Great, thanks!

**Pull request merged**
